Updated help text and set all 3D -> 3d naming convention

diff --git a/mri_3d_photo_recon/mri_3d_photo_recon b/mri_3d_photo_recon/mri_3d_photo_recon
--- a/mri_3d_photo_recon/mri_3d_photo_recon
+++ b/mri_3d_photo_recon/mri_3d_photo_recon
@@ -4,32 +4,124 @@
 set -e
 
 # Make sure FreeSurfer is sourced
-[ ! -e "$FREESURFER_HOME" ] && echo "error: freesurfer has not been properly sourced" && exit 1
+[ ! -e "$FREESURFER_HOME" ] && echo "error: freesurfer has not been properly sourced" && exit 1 
 
 # If requesting help
-if  [ $# == 1 ] && [  $1 == "--help" ]
-then
-  echo " "
-  echo "Bayesian segmentation with histological whole brain atlas."
-  echo " "
-  echo "Next-Generation histological atlas for high-resolution segmentation of human brain MRI"
-  echo "Casamitjana et al. (in preparation)"
-  echo " "
-  echo "Usage:"
-  echo "   segment.sh INPUT_SCAN OUTPUT_DIRECTORY GPU THREADS [BF_MODE] [GMM_MODE]"
-  echo " "
-  echo "INPUT SCAN: scan to process, in mgz or nii(.gz) format"
-  echo "OUTPUT_DIRECTORY: directory with segmentations, volume files, etc"
-  echo "GPU: set to 1 to use the GPU (*highly* recommended but requires a 24GB GPU!)"
-  echo "THREADS: number of CPU threads to use (use -1 for all available threads)"
-  echo "BF_MODE (optional): bias field model: dct (default), polynomial, or hybrid"
-  echo "GMM_MODE (optional): must be 1mm (default) unless you define your own (see documentation)"
-  echo " "
-  exit 0
-fi
+if( $1 == "--help") then
+  echo "3D photo reconstruction + photo imputation / super resolution"
+  echo "Juan Eugenio Iglesias"
+  echo "Friday March 28th 2025"
+  echo ""
+  echo "Run mri_3d_photo_recon with the following options:"
+  echo ""
+  echo "  -h, --help            show help message"
+  echo ""
+  echo ""
+  echo "  --input_photo_dir [INPUT_PHOTO_DIR]"
+  echo "                        Directory with input photos (required)"
+  echo ""
+  echo "  --input_segmentation_dir [INPUT_SEGMENTATION_DIR]"
+  echo "                        Directory with input slab masks / segmentations (required)"
+  echo ""
+  echo "  --hemisphere HEMISPHERE"
+  echo "                        hemisphere; must be left, right, or both (required)"
+  echo ""
+  echo "  --slice_thickness SLICE_THICKNESS"
+  echo "                        Slice thickness in mm (required); will be finetuned if possible"
+  echo ""
+  echo "  --photo_resolution PHOTO_RESOLUTION"
+  echo "                        Resolution of the photos in mm (required)"
+  echo ""
+  echo "  --output_directory OUTPUT_DIRECTORY"
+  echo "                        Output directory with reconstructed photo volume and reference (required)"
+  echo ""
+  echo "  --ref_mri REF_MRI     "
+  echo "                        Reference MRI scan (if available)"
+  echo ""
+  echo "  --ref_mri_synthseg REF_MRI_SYNTHSEG"
+  echo "                        SynthSeg of reference MRI scan (will be computed if it does not exist)"
+  echo ""
+  echo "  --ref_mri_synthsr REF_MRI_SYNTHSR"
+  echo "                        SynthSR of reference MRI; only needed if MRI is not 1mm T1 (will be computed if it does not exist)"
+  echo ""
+  echo "  --low_field_synthsr   "
+  echo "                        Use low-field version of SynthSR (eg for Hyperfine scans)"
+  echo ""
+  echo "  --input_roi_dir INPUT_ROI_DIR"
+  echo "                        Directory with ROi masks to deform to photo reconstruction (optional)"
+  echo ""
+  echo "  --ref_mesh REF_MESH   "
+  echo "                        Reference surface mesh (if available)"
+  echo ""
+  echo "  --mesh_reorient_with_indices MESH_REORIENT_WITH_INDICES"
+  echo "                        Indices to reorient mesh (see PhotoTools page in FreeSurfer wiki)"
+  echo ""
+  echo "  --fresh_tissue        "
+  echo "                        Uses more lenient regularizers to accommodate fresh tissue"
+  echo ""
+  echo "  --photos_of_posterior_side"
+  echo "                        Use when photos are taken of posterior side of slabs (default is anterior side)"
+  echo ""
+  echo "  --order_posterior_to_anterior"
+  echo "                        Use when photos are ordered from posterior to anterior (default is anterior to posterior)"
+  echo ""
+  echo "  --initial_stretch_factor_lr INITIAL_STRETCH_FACTOR_LR"
+  echo "                        Initialize stretch of photos in left-right direction by this factor (useful with squashed brains)"
+  echo ""
+  echo "  --weights WEIGHTS     "
+  echo "                        CSV file with slab weights (follows order of photos). Format is just: weight1,weight2,...,weightN"
+  echo ""
+  echo "  --thickness_cap MAX"
+  echo "                        when using weights, limit the maximum estimated thickness to this value (in mm). "
+  echo "                        This is useful when the geometric estimation of thicknesses is wrong."
+  echo "                        The code (without this option) tries to detect these situations automatically and tells you when to enable this option"
+  echo ""
+  echo "  --equalize_images     "
+  echo "                        Use to equalize images (useful if they have low contrast, but can hurt the machine learning imputation)"
+  echo ""
+  echo "  --skip_bfgs           "
+  echo "                        Use to skip BFGS finetuning (i.e., do only Adam)"
+  echo ""
+  echo "  --threads THREADS     "
+  echo "                        Number of cores to be used. Default is 1. You can use -1 to use all available cores"
+  echo ""
+  echo "  --gpu GPU             "
+  echo "                        Index of GPU to use (default is None, i.e., CPU mode)"
+  echo ""
+  echo "  --deform_recon_dir DEFORM_RECON_DIR"
+  echo "                        Directory with FS dir of reference, to deform surfaces etc (expects to find deform_recon_dir/surf) (optional)"
+  echo ""
+  echo "  --cp_spacing_2d CP_SPACING_2D"
+  echo "                        (Advanced) Control point spacing for 2D deformation"
+  echo ""
+  echo "  --cp_spacing_3d CP_SPACING_3D"
+  echo "                        (Advanced) Control point spacing for 3D deformation"
+  echo ""
+  echo "  --k_lncc_mri K_LNCC_MRI"
+  echo "                        (Advanced) Weight of LNCC between reference MRI and reconstruction"
+  echo ""
+  echo "  --k_dice_mri K_DICE_MRI"
+  echo "                        (Advanced) Weight of Dice between masks of reference and reconstruction"
+  echo ""
+  echo "  --k_dif_slice_loss K_DIF_SLICE_LOSS"
+  echo "                        (Advanced) Weight of SSD between consecutive slices of reconstruction"
+  echo ""
+  echo "  --k_mesh_loss K_MESH_LOSS"
+  echo "                        (Advanced) Weight of absolute distance to edge of masks from mesh vertices"
+  echo ""
+  echo "  --k_regularizer K_REGULARIZER"
+  echo "                        (Advanced) Weight of regularizer of log_det(affine matrices)"
+  echo ""
+  echo "  --k_regularizer_nonlin K_REGULARIZER_NONLIN"
+  echo "                        (Advanced) Weight of regularizer of 2D nonlinear deformation of photos"
+  echo ""
+  echo "  --k_regularizer_nonlin3d K_REGULARIZER_NONLIN3D"
+  echo "                        (Advanced) Weight of regularizer of 3D nonlinear deformatin of reference"
+exit 0
+endif
 
 # Find path to shell script
-SCRIPTPATH="$FREESURFER_HOME_FSPYTHON/python/packages/3D_photo_recon/scripts/recon_case.py"
+SCRIPTPATH="$FREESURFER_HOME_FSPYTHON/python/packages/3d_photo_recon/scripts/recon_case.py"
 
 # Try to find atlas data
 MODELPATH="$FREESURFER_HOME/models/photo_imputation_unet.pth"
