handle dicom files with space in the names when using dcm2niix for pre-processing   - nii_dicom_batch.cpp/dcm2niix_fswrapper.cpp: output imagelist and series-info as csv   - dcmunpack:     1. parse imagelist and series-info using comma as delimiter (awk -F,)     2. change how mri_convert submission string is construected so that quotes around the dicom files can be preserved     3. put single quotes around dicom file in summary reports     4. these changes fix the bug that wrong dicom counts are reported in pre-process/scan-only summary

diff --git a/scripts/dcmunpack b/scripts/dcmunpack
--- a/scripts/dcmunpack
+++ b/scripts/dcmunpack
@@ -138,30 +138,34 @@ endif
 
 echo "Searching for matching files" | tee -a $LF
 date | tee -a $LF
-set flist = ();
-foreach d ($SrcDirList2)
-  #echo "Searching $d" >> $LF
-  if($#SrcPre || $#SrcPat || $#SrcExt) then
-    set flist0 = (`find -L $d -name "$SrcPre*$SrcPat*$SrcExt"`)
-  else
-    set flist0 = (`find -L $d`)
-  endif
-  if($OnePerDir && $#flist0 > 0) then
-    set flist0 = ($flist0[1]);
-  endif
-  set flist = ($flist $flist0);
-end
+if(! $dcm2niix_dicom_dump) then
+  # this section of codes don't handle dicoms with space in the name correctly
+  # since it is only needed when not using dcm2niix, skip the section when using dcm2niix
+  set flist = ();
+  foreach d ($SrcDirList2)
+    #echo "Searching $d" >> $LF
+    if($#SrcPre || $#SrcPat || $#SrcExt) then
+      set flist0 = (`find -L $d -name "$SrcPre*$SrcPat*$SrcExt"`)
+    else
+      set flist0 = (`find -L $d`)
+    endif
+    if($OnePerDir && $#flist0 > 0) then
+      set flist0 = ($flist0[1]);
+    endif
+    set flist = ($flist $flist0);
+  end
 
-#date | tee -a $LF
+  #date | tee -a $LF
 
-echo "Found $#flist total files." | tee -a $LF
-if($#flist == 0) then
-  echo "ERROR: did not find any files"| tee -a $LF
-  exit 1;
-endif
-if($#flist > 100 && $#SrcInfo == 0) then
-  echo "  Interrogating each and every one of them."
-  echo "  Be patient." 
+  echo "Found $#flist total files." | tee -a $LF
+  if($#flist == 0) then
+    echo "ERROR: did not find any files"| tee -a $LF
+    exit 1;
+  endif
+  if($#flist > 100 && $#SrcInfo == 0) then
+    echo "  Interrogating each and every one of them."
+    echo "  Be patient." 
+  endif
 endif
 
 # Go through each file, create an info dump, extract params. 
@@ -218,7 +222,7 @@ rm -f $SeriesInfo
 if($DoCopy) then
   if(-e $infofile) then
     echo "use information in $infofile to copy DICOMs ..."
-    set SeriesNos = (`cat $infofile | awk '{print $2}' | sort -n | uniq`)
+    set SeriesNos = (`cat $infofile | awk -F, '{print $2}' | sort -n | uniq`)
     echo "Found $#SeriesNos unique series: $SeriesNos" | tee -a $LF
     goto do_unpack;
   endif
@@ -235,6 +239,7 @@ endif
 # if --dcm2niix, use mri_probedicom --dcm2niix-dicom-dump dicom-dir $SeriesInfo #
 #################################################################################
 if($dcm2niix_dicom_dump) then
+  # imagelist and series-info are output as csv files, parse them using comma as delimiter (awk -F,)
   # this environment variable will be pick up by dcm2niix to output $infofile
   setenv MGH_DCMUNPACK_IMAGELIST $infofile
   if(-e $infofile) rm -f $infofile
@@ -250,7 +255,7 @@ if($dcm2niix_dicom_dump) then
     $cmd |& tee -a $LF
 
     # print all the unique series
-    set SeriesNos = (`cat $SeriesInfo | awk '{print $1}' | sort -n | uniq`)
+    set SeriesNos = (`cat $SeriesInfo | awk -F, '{print $1}' | sort -n | uniq`)
     echo "Found $#SeriesNos unique series: $SeriesNos" | tee -a $LF
 
     ##### ???
@@ -261,7 +266,7 @@ if($dcm2niix_dicom_dump) then
     ##### ???
 
     foreach series ($SeriesNos)
-      set descr = `cat $SeriesInfo | awk -v s=$series '{if($1 == s) print $2}' | head -n 1 | sed 's/*//g'| sed "s/'//g"`
+      set descr = `cat $SeriesInfo | awk -F, -v s=$series '{if($1 == s) print $2}' | head -n 1 | sed 's/*//g'| sed "s/'//g"`
       if($DoAutoRunSeq) then
         if("$descr" == Localizer || "$descr" == Localizer_aligned || "$descr" == localizer || "$descr" == AAHScout || \
            "$descr" == AAHScout_sag || "$descr" == AAHScout_cor || \
@@ -281,7 +286,7 @@ if($dcm2niix_dicom_dump) then
       endif
     end  # foreach series ($SeriesNos)
   end # foreach d ($SrcDirList2)
-else
+else # BEGINNING OF dcm2niix_dicom_dump=0 PRE-PROCESSING
   # for each dicom found, (mri_probedicom --i $f --d filetype)
   #   retrieve the following fields:  (mri_probedicom --i $f --no-siemens-ascii)
   #     SeriesNo|PatientName|StudyDate|StudyTime|Institution|EchoTime|RepetitionTime|FlipAngle|PixelSpacing|PhaseEncDir|PixelFrequency|ImageType
@@ -459,20 +464,22 @@ else
     endif
   end
 endif  # dcm2niix_dicom_dump=0
+# END OF PRE-PROCESSING
 
 # start printing series summary for pre-processed dicoms (mri_probedicom)
 echo "" | tee -a $LF
 echo "DICOM Pre-process Summary:" | tee -a $LF
 set ScanOnlySummary = "$TargetDir/log/ScanOnly-Summary.txt"
 foreach series ($SeriesNos)
-  set protocol = `cat $SeriesInfo | awk -v s=$series '{if($1 == s) print $2}' | head -n 1`
-  set dicomfpath = `cat $SeriesInfo | awk -v s=$series '{if($1 == s) print $9}' | head -n 1`
-  set dicomfile  = `basename $dicomfpath`
-  set ndicomfiles = `cat $infofile | awk -v r=$series '{if($2 == r) print $11}' | wc -l | awk '{print $1}'`  
+  set protocol = `cat $SeriesInfo | awk -F, -v s=$series '{if($1 == s) print $2}' | head -n 1`
+  set dicomfpath = `cat $SeriesInfo | awk -F, -v s=$series '{if($1 == s) print $9}' | head -n 1`
+  set dicomfile  = `basename "$dicomfpath"` # quotes around the variable to handle dicoms with space in the name
+  set ndicomfiles = `cat $infofile | awk -F, -v r=$series '{if($2 == r) print $11}' | wc -l | awk '{print $1}'`
       
   # create unpacksdcmdir like summary instead
   # seriesno protocol-name num-dicom-files first-dicom-file
-  printf "  %-4d %40s %6d %s\n" $series $protocol $ndicomfiles $dicomfile >> $ScanOnlySummary
+  # quotes around the variable to handle dicoms with space in the name
+  printf "  %-4d %40s %6d '%s'\n" $series $protocol $ndicomfiles "$dicomfile" >> $ScanOnlySummary
 end  # end printing series summary
 cat $ScanOnlySummary | tee -a $LF
 
@@ -571,7 +578,7 @@ foreach run ($RunNos)
 
   if($DoConvert) then
     if ($dcm2niix_dicom_dump) then
-      set f = `cat $SeriesInfo | awk -v r=$run '{if($1 == r) print $9}' | head -n 1`
+      set f = `cat $SeriesInfo | awk -F, -v r=$run '{if($1 == r) print $9}' | head -n 1`
       # PatientName is printed out differently in imagelist.dat, can't use imagelist.dat to retrieve dicom file
       #set f = `cat $infofile | awk -v r=$run '{if($4 == r) print $13}' | head -n 1`
     else
@@ -586,7 +593,7 @@ foreach run ($RunNos)
         # ORIGINAL_PRIMARY_M_ND_NORM
         # ORIGINAL_PRIMARY_DIFFUSION_NONE_ND_NORM_MFSPLIT
         set PhaseStr = ""
-        set ImageType = `cat $SeriesInfo | awk -v r=$run '{if($1 == r) print $10}'`
+        set ImageType = `cat $SeriesInfo | awk -F, -v r=$run '{if($1 == r) print $10}'`
         if($#ImageType == 1) then
           if($ImageType == "ORIGINAL_PRIMARY_P_ND") set PhaseStr = "_phase"
           if($ImageType == "ORIGINAL_PRIMARY_P_NONE") set PhaseStr = "_phase"
@@ -598,7 +605,7 @@ foreach run ($RunNos)
       endif
     endif
 
-    set tSequenceFileName = `cat $SeriesInfo | awk -v r=$run '{if($1 == r) print $11}'`
+    set tSequenceFileName = `cat $SeriesInfo | awk -F, -v r=$run '{if($1 == r) print $11}'`
 
     set outfname = "$outdir/$FName$PhaseStr.$Format"
     echo $outfname
@@ -606,27 +613,28 @@ foreach run ($RunNos)
     echo "#@# Run $run `date` ==================================" |& tee -a $LF
     set ud = (`UpdateNeeded $outfname "$f"`)
     if($ud || $ForceUpdate) then
-      set cmd = (mri_convert "$f" $outfname --nskip $NSkip --ndrop $NDrop $itdicom)
-      if($#iid) set cmd = ($cmd -iid $iid);
-      if($#ijd) set cmd = ($cmd -ijd $ijd);
-      if($#ikd) set cmd = ($cmd -ikd $ikd);
-      if($DoFirstDicom) set cmd = ($cmd --first-dicom $outdir/log/$FName.first.dicom.path)
+      # construction of mri_convert submission string is changed so that the quotes around dicom file are preserved
+      set convert_args = ($outfname --nskip $NSkip --ndrop $NDrop $itdicom)
+      if($#iid) set convert_args = ($convert_args -iid $iid);
+      if($#ijd) set convert_args = ($convert_args -ijd $ijd);
+      if($#ikd) set convert_args = ($convert_args -ikd $ikd);
+      if($DoFirstDicom) set convert_args = ($convert_args --first-dicom $outdir/log/$FName.first.dicom.path)
       if($UseDCM2NIIX) then
-        set cmd = ($cmd -dcm2niix)
+        set convert_args = ($convert_args -dcm2niix)
         if($dcm2niix_CreateBIDS) then
-          set cmd = ($cmd -dcm2niix-createBIDS --dcm2niix-outdir $outdir)
+          set convert_args = ($convert_args -dcm2niix-createBIDS --dcm2niix-outdir $outdir)
         endif
 	
         if($dcm2niix_no_ForceStackSameSeries) then
-          set cmd = ($cmd -dcm2niix-no-ForceStackSameSeries)
+          set convert_args = ($convert_args -dcm2niix-no-ForceStackSameSeries)
         endif
 	
         if($dcm2niix_dicom_dump) then
 	  set dicomflst = $dicomflstDir/$run-dicomflst.txt
           set dumpfile = $outdir/log/$FName-infodump.dat
-          set cmd = ($cmd --dcm2niix-dicom-flist $dicomflst --dcm2niix-info-dump $dumpfile)
+          set convert_args = ($convert_args --dcm2niix-dicom-flist $dicomflst --dcm2niix-info-dump $dumpfile)
 
-          if($DoSiemensAscii) set cmd = ($cmd -siemens-ascii-dump)
+          if($DoSiemensAscii) set convert_args = ($convert_args -siemens-ascii-dump)
 
 	  set localDcm2niixOpts = ($Dcm2niixOpts)
 	  if("$tSequenceFileName" == "%SiemensSeq%\gre_b0map") then
@@ -639,24 +647,27 @@ foreach run ($RunNos)
         endif
 	
 	if($#localDcm2niixOpts) then
-	  set cmd = ($cmd --dcm2niix-opts $localDcm2niixOpts)
+	  set convert_args = ($convert_args --dcm2niix-opts $localDcm2niixOpts)
 	endif
       endif
-      if(! $UseDCM2NIIX) set cmd = ($cmd -no-dcm2niix)
-      if($siemensBVecsCross)   set cmd = ($cmd -siemensBVecsCross)
-      if(! $siemensBVecsCross) set cmd = ($cmd -no-siemensBVecsCross)
+      if(! $UseDCM2NIIX) set convert_args = ($convert_args -no-dcm2niix)
+      if($siemensBVecsCross)   set convert_args = ($convert_args -siemensBVecsCross)
+      if(! $siemensBVecsCross) set convert_args = ($convert_args -no-siemensBVecsCross)
 
       # retrieve information for DoConvertSummary
-      set protocol = `cat $SeriesInfo | awk -v s=$run '{if($1 == s) print $2}' | head -n 1`
-      set dicomfile  = `basename $f`
+      set protocol = `cat $SeriesInfo | awk -F, -v s=$run '{if($1 == s) print $2}' | head -n 1`
+      set dicomfile  = `basename "$f"` # quotes around the variable to handle dicoms with space in the name
       set okstatus = 'ok'
       set cols = 0
       set rows = 0
       set slice = 0
       set nframes = 0
 
-      echo $cmd |& tee -a $LF
-      $cmd |& tee -a $LF
+      # to preserve the quotes around the dicom file, which is needed for dicoms with space in the name,
+      # the quoted dicom file needs to be passed to mri_convert directly.
+      # include it in the argument string will have the file name expanded by the shell
+      echo "mri_convert $f $convert_args" |& tee -a $LF
+      mri_convert "$f" $convert_args |& tee -a $LF
       
       # create unpacksdcmdir like summary for series converted
       # the summary is saved to $DoConvertSummary
@@ -673,7 +684,8 @@ foreach run ($RunNos)
 	  set nframes = `echo $dims | awk '{print $4}'`
 	endif
       endif
-      printf "  %-4d %40s %3s %3d %3d %3d %3d %s\n" $run $protocol $okstatus $cols $rows $slice $nframes $dicomfile >> $DoConvertSummary
+      # quotes around the variable to handle dicoms with space in the name
+      printf "  %-4d %40s %3s %3d %3d %3d %3d '%s'\n" $run $protocol $okstatus $cols $rows $slice $nframes "$dicomfile" >> $DoConvertSummary
       
       if($status) then
         if($ExitOnError) then
@@ -705,15 +717,21 @@ foreach run ($RunNos)
 
   if($DoCopy) then
     set okstatus = 'ok'
-    set flist = (`cat $infofile | awk -v r=$run '{if($2 == r) print $11}'`);
+    if(! $dcm2niix_dicom_dump) then
+      set flist = (`cat $infofile | awk -F, -v r=$run '{if($2 == r) print $11}'`)
+    else
+      set dicomflst = $dicomflstDir/$run-dicomflst.txt
+      set flist = ("`cat $dicomflst`") # this will put quotes around this line
+    endif
 
     # retrieve information for DoCopySummary
-    set dicomfpath  = `cat $infofile | awk -v r=$run '{if($2 == r) print $11}' | head -n 1`
-    set dicomfile = `basename $dicomfpath`
-    set ndicomfiles = `cat $infofile | awk -v r=$run '{if($2 == r) print $11}' | wc -l | awk '{print $1}'`
+    set dicomfpath  = `cat $infofile | awk -F, -v r=$run '{if($2 == r) print $11}' | head -n 1`
+    set dicomfile = `basename "$dicomfpath"` # quotes around the variable to handle dicoms with space in the name
+    set ndicomfiles = `cat $infofile | awk -F, -v r=$run '{if($2 == r) print $11}' | wc -l | awk '{print $1}'`
       
-    foreach f ($flist)
-      cp $f $outdir |& tee -a $LF
+    # ':q' and quotes around $f are needed to handle dicoms with space in the name
+    foreach f ($flist:q)
+      cp "$f" $outdir |& tee -a $LF
       if($status) then
         set okstatus = 'err'
         if($ExitOnError) then
@@ -730,13 +748,14 @@ foreach run ($RunNos)
     # the summary is saved to $DoCopySummary
     # it will be concatenated to main log at the end of dcmunpack
     # seriesno copy-status num-dicom-files first-dicom-file
-    printf "  %-4d %3s %6d %s\n" $run $okstatus $ndicomfiles $dicomfile >> $DoCopySummary
+    # quotes around the variable to handle dicoms with space in the name
+    printf "  %-4d %3s %6d '%s'\n" $run $okstatus $ndicomfiles "$dicomfile" >> $DoCopySummary
   endif
 
   if(! $dcm2niix_dicom_dump) then
     # mri_probedicom --i $f --no-siemens-ascii
     if($DoInfoDump) then
-      set f = `cat $infofile | awk -v r=$run '{if($2 == r) print $11}' | head -n 1`
+      set f = `cat $infofile | awk -F, -v r=$run '{if($2 == r) print $11}' | head -n 1`
       set dumpfile = $outdir/log/$FName-infodump.dat
       set ud = (`UpdateNeeded $dumpfile $f`)
       if($ud || $ForceUpdate) then
@@ -751,7 +770,7 @@ foreach run ($RunNos)
   endif
 
   if($DoFIPS) then
-    set f = `cat $infofile | awk -v r=$run '{if($2 == r) print $11}' | head -n 1`
+    set f = `cat $infofile | awk -F, -v r=$run '{if($2 == r) print $11}' | head -n 1`
     # Get full path 
     set fd = `dirname $f`;
     pushd $fd > /dev/null
