tksurferfv. Now will automatically switch SUBJECTS_DIR to FS/subjects if subject cannot be found and it is fsaverageX or fsmni152

diff --git a/scripts/tksurferfv b/scripts/tksurferfv
--- a/scripts/tksurferfv
+++ b/scripts/tksurferfv
@@ -366,8 +366,13 @@ if($subject == getreg) then
   set subject = `reg2subject $overlayreg`
 endif
 if(! -e $SUBJECTS_DIR/$subject) then
-  echo "ERROR: cannot find $subject"
-  exit 1;
+  set a = `echo $subject | cut -c1-9`
+  if($a == fsaverage || $subject == fsmni152) then
+    setenv SUBJECTS_DIR $FREESURFER/subjects
+  else
+    echo "ERROR: cannot find $subject"
+    exit 1;
+  endif
 endif
 set surflist = ();
 foreach surf ($surflist0)
